name: Test code excersises

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Get branch name
        id: branch_name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Extract folder name
        id: folder_name
        run: |
          FOLDER_NAME=$(echo $BRANCH_NAME | sed 's/feature\/\(.*\)/\1/')
          echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_ENV
          
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --force

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml --export-type Coveralls

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/kcov/merged/coverage.lcov

      - name: Change directory and run tests
        run: cd exercises && cd $FOLDER_NAME && cargo test --verbose      
